name: verify
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          python-version: "3.12"
          cache-pip: true

      # Initialize your own environment for resolving.
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('Examples/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: setup CompetitiveVerifierCsResolver
        run: |
          dotnet build Sources/CompetitiveVerifierCsResolver/CompetitiveVerifierCsResolver.csproj -c Release -o '${{runner.temp}}/localbin'
          ln -s CompetitiveVerifierCsResolver '${{runner.temp}}/localbin/competitive-verifier-cs-resolver'
          echo '${{runner.temp}}/localbin' >> $GITHUB_PATH

      - name: Test Example.Mtp
        working-directory: Example.Mtp
        run: |
          dotnet test --solution Example.Mtp.slnx --report-competitive-verifier="${{runner.temp}}/Unittest.Mtp"

      - name: Test Example.VsTest
        working-directory: Example.VsTest
        run: |
          dotnet test Example.VsTest.slnx --logger "CompetitiveVerifier;OutDirectory=${{runner.temp}}/Unittest.VsTest"

      - name: Problems Example.Mtp
        run: |
          dotnet run --project Example.Mtp/VerifyApp.Mtp/VerifyApp.Mtp.csproj -c Release --no-launch-profile | tee "${{runner.temp}}/problems.Mtp.json"

      - name: Problems Example.VsTest
        run: |
          dotnet run --project Example.VsTest/VerifyApp.VsTest/VerifyApp.VsTest.csproj -c Release --no-launch-profile | tee "${{runner.temp}}/problems.VsTest.json"

      - name: cs-resolve-mtp
        uses: competitive-verifier/actions/cs-resolve@v2
        with:
          solution: Example.Mtp/Example.Mtp.slnx
          output-path: verify_files.Mtp.json
          # Specify patterns
          include: |
            Example.Mtp/**
          # exclude: your-own-exclude/
          unittest-result: ${{runner.temp}}/Unittest.Mtp/*.csv
          problems: ${{runner.temp}}/problems.Mtp.json
      - name: cs-resolve-vstest-old-style
        uses: competitive-verifier/actions/cs-resolve@v2
        with:
          solution: Example.VsTest/Example.VsTest.sln
          output-path: verify_files.VsTest.old.json
          # Specify patterns
          include: |
            Example.VsTest/**
          # exclude: your-own-exclude/
          unittest-result: ${{runner.temp}}/Unittest.VsTest/*.csv
          problems: ${{runner.temp}}/problems.VsTest.json
      - name: cs-resolve-vstest-new-style
        uses: competitive-verifier/actions/cs-resolve@v2
        with:
          solution: Example.VsTest/Example.VsTest.slnx
          output-path: verify_files.VsTest.json
          # Specify patterns
          include: |
            Example.VsTest/**
          # exclude: your-own-exclude/
          unittest-result: ${{runner.temp}}/Unittest.VsTest/*.csv
          problems: ${{runner.temp}}/problems.VsTest.json

      - name: diff verify_files.json
        id: diff-json
        uses: josephburnett/jd@v2.5.0
        with:
          args: -mset verify_files.VsTest.json verify_files.VsTest.old.json
      - name: Check verify_files.json
        run: |
          echo '${{ steps.diff-json.outputs.output }}'
          if [ "${{ steps.diff-json.outputs.exit_code }}" != "0" ]; then exit 1; fi

      - name: Merge verify-files
        uses: competitive-verifier/actions/merge-verify-files@v2
        with:
          verify-files: verify_files.VsTest.json verify_files.Mtp.json
          output-path: verify_files.json

      - name: Upload verify_files.json
        uses: competitive-verifier/actions/upload-verify-artifact@v2
        with:
          file: verify_files.json

      - name: Check bundled
        id: test-bundled
        run: |
          echo "count=$(find .competitive-verifier/bundled/ -type f | wc -l)" >> $GITHUB_OUTPUT
      - name: Upload bundled
        uses: actions/upload-artifact@v7
        if: steps.test-bundled.outputs.count > 0
        with:
          name: Bundled-${{ runner.os }}
          path: .competitive-verifier/bundled
          retention-days: 1

  verify:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v6

      - name: Download verify_files.json
        uses: competitive-verifier/actions/download-verify-artifact@v2

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          python-version: "3.9"
          cache-pip: true

      # Initialize your own environment for verification.
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('Examples/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: |
          dotnet build Example.VsTest/Example.VsTest.slnx -c Release
          dotnet build Example.Mtp/Example.Mtp.slnx -c Release

      - name: Verify
        uses: competitive-verifier/actions/verify@v2
        with:
          destination: ${{runner.temp}}/result.json

      - name: Upload result artifact
        uses: actions/upload-artifact@v7
        with:
          name: Result-${{ runner.os }}-${{ matrix.index }}
          path: ${{runner.temp}}/result.json
          retention-days: 1

  docs-and-check:
    runs-on: ubuntu-latest
    needs: [ verify ]
    steps:
      - uses: actions/checkout@v6

      - name: Download verify_files.json and all artifacts
        id: all-artifacts
        uses: competitive-verifier/actions/download-verify-artifact@v2
        with:
          download-all: true
          artifact-root: .artifacts/

      - name: Extract bundled
        shell: bash
        run: |
          rm -rf .competitive-verifier/bundled
          if test -d "$SRCDIR"; then
            mkdir -p .competitive-verifier/
            mv "$SRCDIR" .competitive-verifier/bundled
          else
            echo "$SRCDIR is not exists."
          fi
        env:
          SRCDIR: .artifacts/Bundled-${{ runner.os }}

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          python-version: "3.9"
          cache-pip: true

      - name: Docs
        uses: competitive-verifier/actions/docs@v2
        with:
          verify-result: ${{ steps.all-artifacts.outputs.artifacts-root
            }}/Result-*/result.json
          destination: _jekyll
          write-summary: true

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: _jekyll
          destination: _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - name: Check
        uses: competitive-verifier/actions/check@v2
        with:
          verify-result: ${{ steps.all-artifacts.outputs.artifacts-root
            }}/Result-*/result.json
  deploy:
    if: (success() || failure()) && github.ref == 'refs/heads/main'
    needs: docs-and-check
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
